### ISSUE TITLE
Cubing three "Hatred's Reflection" shards does not yield one Lilith's Mirror, despite the description telling so.

### ISSUE THREAD

**Issue by PerAstraAdDeum** [Lukaszpg/PD2-Single-Player-Plus-mod#4]
Cubing three "Hatred's Reflection" shards does not yield one Lilith's Mirror, despite the description telling so.

**Comment by PerAstraAdDeum** [comment]
Update: cubing FIVE "Hatred's Reflection" does yield one Lilith's Mirror.

**Comment by Lukaszpg** [comment]
Fixed in 9.0.0.
