### ISSUE TITLE
Cubing three "Dark Alchemist" shards does not yield one Vial of Lightsong, despite the description telling so.

### ISSUE THREAD

**Issue by PerAstraAdDeum** [Lukaszpg/PD2-Single-Player-Plus-mod#6]
Cubing three "Dark Alchemist" shards does not yield one Vial of Lightsong, despite the description telling so.

**Comment by PerAstraAdDeum** [comment]
Update: cubing FIVE "Dark Alchemist" does yield one Vial of Lightsong.

**Comment by Lukaszpg** [comment]
Fixed in 9.0.0.
