### ISSUE TITLE
Using Mythic Orb on a magic Cryptic Axe to create the unique Polearm "Tomb Reaver" fails

### ISSUE THREAD

**Issue by PerAstraAdDeum** [Lukaszpg/PD2-Single-Player-Plus-mod#8]
Using Mythic Orb on a magic Cryptic Axe to create the unique Polearm "Tomb Reaver" fails. Instead, a random rare is created.

**Comment by PerAstraAdDeum** [comment]
Using Mythic Orb on a white Cryptic Axe fails as well. Again, a random rare is created instead.

**Comment by Lukaszpg** [comment]
Fixed in 9.0.0.
